---
- name: Install Docker and Set Up MongoDB Container
  hosts: db_server
  become: yes
  vars_files:
    - secret.yaml
  tasks:
    - name: Pull MongoDB Docker image
      docker_image:
        name: mongo
        tag: latest

    - name: Run MongoDB container
      docker_container:
        name: mongodb
        image: mongo:latest
        state: started
        restart_policy: always
        published_ports:
          - "27017:27017"
        environment:
          MONGO_INITDB_ROOT_USERNAME: "{{ mongo_root_user }}"
          MONGO_INITDB_ROOT_PASSWORD: "{{ mongo_root_password }}"
        volumes:
          - "/data/db:/data/db"
          
    - name: Execute commands inside MongoDB container
      docker_container:
        name: mongodb
        state: started
        interactive: yes
        tty: yes
        command: mongosh -u "{{ mongo_root_user }}" -p "{{ mongo_root_password }}" --eval "{{ item }}"
      with_items:
        - "use travelmemory"
        - 'db.createUser({ user: "{{ mongo_user_name }}", pwd: "{{ mongo_user_password }}", roles: [{ role: "readWrite", db: "travelmemory" }] })'
        - 'db.createCollection("users")'

  handlers:
    - name: restart MongoDB
      service:
        name: mongod
        state: restarted
